### ISSUE TITLE
UI - Unable to click Glyphs when bottom buttons are "locked" (pressed) - Noticed During Cel 7

### ISSUE THREAD

**Issue by bparrish** [antimatter-dimensions/mobile-issues#710] opened 2024-04-11 13:53 UTC
**Is your feature request related to a problem? Please describe.**
When using the swipe "feature" on the bottom buttons, it seems that the the Glyph tooltips are disabled. 
This was mainly noticed on my most recent Cel 7 playthrough when attempting to Armageddon to unequip a glyph, while have MAX or one of the bottom buttons "active", I wasn't able to tap another Glyph to equip it

**Describe the solution you'd like**
See if you're able to re-enable the Glyph tooltips after they get unequipped or on glyph unequip, deactivate the active bottom button, ie MAX, RG, etc. 

**Describe alternatives you've considered**
Player has to figure out how to remove the active on the buttons, by tapping it again? and then be able to work with glyphs.
Alternatively, double tapping a glyph with still equip it in this state.

**Comment by kajfik** [comment] 2024-07-08 12:47
not able to reproduce, closing

**Closed as completed by kajfik** 2024-07-08 12:47 UTC
Labels: ui improvement
