### ISSUE TITLE
while/until total tt loop doesn't terminate properly

### ISSUE THREAD

**Issue by Calmcat5** [antimatter-dimensions/mobile-issues#583] opened 2023-03-28 16:50 UTC
to reproduce:
1. import save
2. reset reality
3. wait for script to reach lines 141-142
4. observe non-terminating behavior

notes:
- my script sucks and may require the ocassional infinity or eternity. sorry
- this behavior has been observed for until, while, formatted number, and unformatted. i honestly have no clue what is happening here
- IMPORTANT: i have noticed the the loop does terminate at some point past 16k-17k total tt but i'm not quite sure what number and why
- below screenshot displays the afflicted loop (with some extra lines cuz thanks pixel markdown)

![Screenshot_20230328-100029](https://user-images.githubusercontent.com/94936969/228303074-d6db6d80-9cd1-4d56-8de8-8a922d2a9ec5.png)

save:
``AntimatterDimensionsAndroidSaveFormatAAAH4sIAAAAAAAAAO1dbXPbtrL0bKx50cVjV4B9hvjuOmmWlOfW33nA9p5g4j0aRZPJFJXopL4pv7vdxcgQYCkJNqJ2547cZvEBMnFg8ViX0cCy0cHKazhZ59jFbZUW1Pf3xLZNy8tg0cVE6I0b0b0cd5DQtqnyVVlW2Of3xy2n2eV0aWQPr0aR84U1zyhk9MVPrLdplA2ZQnhShFitFaKP8Dru6rEFwHWTb5CIkYmeqoFI0aRSmSRaTzqYq80auw3qLfJEv0ayovCySw2i2rfL3MkYScnObbs1mVf8zc41jRdpYV20crhZbqtbvLZh9MfyZQMPPw0bvzvf7IrZwkJblTtsUdg6yjkPW0aanlDN4cVXOgQqbnAJT4Bc5hfZ0c0cjm0cW2TbLgVGYgIEXp0bVW8s6rYzFVQBbP6ZLuE0as0aL24b9Pl1gJfprMPP5fL7LL8hJx40b6XXuF4JdOI83Xx4YzvxZb7ajuHQvGb9b0bu7TTrPtraq9iU2FVoLlSimKGXaaHVBB8j8Ka9g0b0cLVi7J0aXfB0bd0c8m0cfzas9a27y5dpp9zbIYBLuervHpZv7KtmVsX0cwYdtnzln65vrdLPwfOi6Ugm1ZFubFpAhSQHGo0aNcNLrGP10bt4SXJWWub34rluXsQzZvxoaTQiS0aydL50cU3pHvBwHToBcka0bDb7viP40aREYk9Dui0c80bIBOH674XoMI0bsft2m75fZeQnasdjtVr6ubNagyma1fbd1ZOs3YK0c9PUBQ5NX9PmsbWUpiLWXH0aFIkusfQkgFD27ec1gLc7zUQVvkP6f22TBOv94k4Zr8ta7kC7cIN2nulhxX0c3fJ0bvTgDJ0bl8maWFr9gWn5fLZbreZnHpdbnBVgOtVXqXF0bnmPrLRR92Bv1vJO0bTjbY7y4ZyTnqOhlIH0cjQA3gMtRTsPf741BL0bv5H0aDmRkMRVMayHolWmtzgs4MNFcrqwMDcN7Jqkn0bGFL7D2iAImCGoPa7pszFym8420bW0a0by7rhyBFV1hvz27y42y3TTd0aPvfsVoNiuM9T4Xw7o0cyMGgH4r3xQ1MIzMpvr6ck9EYBQl0cHHu0cZ0cwCo5VpggEEWNH990b1kuOvvHNddLPIyk3mgr3OExhHpgVI1Gund611i0a1qKMV6KqA6QZgQSRg741vEXl840b27pUEKDMNUKSYqV22gS7jMknoYqBNyL3aYTbCpo1tySbwQ4urdepGgWEwGeFJ8KUv9AYLbGuLh9FivbReMHWRoBkiPgEAeHDsEhHg5V0aP0cJFGw0b0ckhuenD6aN4FzEI34DLdbbM3boQHt0c6R3aUOo0cWE2mkAfLwZmXHpjXWcnGAmYKqY0aCiYzg95v0ak0ctO0bBGvlQy8L9VQb0bETp7OMDNRE8ozgJFj9TteZFjMCwp4Jxl8HyVA0cusIN3egnK7s94eNOls0cu0cdtnqF1uZfGXhw7RyP82dmIKfXWQWe5Z193Vujbb5aL7OL29tsVp0a7rxFKq0cu1k9d6CsTWh0a8sStDN9o7lOvzle9QWrKwZDEsg6n7vpg3CUmg0cJa15yzr1u2uLulMZiSoivUpIXAHaho21AjcLoLUol0a7it0ag6LILnGtYPNrdxn8IWN2UgyVmv8PVlrwj0bDfgzotlRpaRbIYkrIwMVPab5V87oN3OBPQ5s2vu14aybF9wIuRMUz6u7NC0bG7ljpXGYfs0bV4rvSBkD4IMgiA7K38MZxyo36ARWgTQhbgdcwrLMFILRonWHhxOZ4BvhoSVUG65ElL0bjHNexnMCPea2MxZvrxpVXld5KK0cgFjn0cs3NXVb0aSlt0bjWh5WDs5UDPp1Uo6NT6GIRetru3xo9bD1iwsrDFuonZ3Y7PqltQhQVwYzM53b92Wm7uyqgLW1TfC0bcwOtWA9YSxr0bw0ahUSNItwFkGDwZAk4GQZNBwI0cTWT7SGtBX9l5Pw0chg6q47E1GXb8pPNFZktvjlTdhzo0cRUDwAZqJz0aKyb9Sh0cDlfPdZusCmx5TZvZWr0bWueECg3I0agWIrKH6O0aujWToVrJQI0akrO1RbChX67TYp8hmzV1wGiHmXDuN56O70buajWjhIkXSojW0cBQzN1dbNJt4s3jcd2Fzl5oBPtIglOB9b0cBoECXqPBw90csLAKYvutFupl3gpGBiBrCD88O50a87XxTvQX8t0a49OxND7vK4AO45F0c4b1xvzoDLi6BHitGN1my0brCT1yGM3A0cQxCwfQXeuGPhAi7r0bt2FC8cvN0bUdcGzbzicAmitwlFOM0c1sHbIsIB0asi1OuanK8pZMIWGzmva3IXP20awqrG9PE2SptSRROMLpDJ8JIxK0aOUHZ0c90cs0a2JbXS0bhGP5Ms2rbJnaTk0a3Hy6KbHN3X1fYri4e7bn2UTcpZaOZeX57m80cg0bv7GzqeQ3nqYX9zd7okJG9f65cVA2ZuoDN2O67yYZb9AYP3beu78VcQxamraxo0cf4fyHwHmHCqHalOtGVm0bBDoSq526420cHBVTszdr7IMDh0ck2M8C1Sb0aYsLwOOlPBqafrIv99SCCcDzdP26mIFF3dYtDu7hTL9VDOhcbtfLFILzbbnbzOrweFF0bOm0cVFpbAC79u5vUYwqvgBZzJW0bTbfsvhxjpbLjNnJ9ySg1WffSckvw3Wy3e0boxorNC0cLVaBBnev7KgNdkYL2sSTdRTZ0cFRrbev6EBHOsZ0cGUDNjbooreaedRmtr7GtLp0bLFGJZz4IJPef3buGQyhI1WVVbo827M3ZoC6fb4xJ5dlXlTHEdl3msh0c1Du2GasitU9aUau7DHp2kZZbtxMn4uxtvlweRbLOQIaKKr3LrtfuGUs7m0b9m2fymbNYG5tksvX0cmOtYpCF350bZlrgZ4Gv672z56xno0cpzC6nPmMlD0bFIffvOuni2wuVska3unX2tlWn9fuM51CPr0b0c3v90c0cC0b6B4QXlt7rK510bxgDl2RHy8LtzXgKgNtaaP9f6bLXRbOy9TU0ceR0avTmimVe1l2s3pVzDCOYcbUkV0bMOrEivZrbyPjKMx0cfAq9VNe1JVV0c8qrxVWGhjWb0bbALyrtT5bPFrvgQOT91YI5bLLMVRAStN4KX90bf4QlwUvN4Jhb49dbBl2TZ9Htofn4PskcCxbc97EKSzN9dZ5cIhvLzaFWdvjq6Nowd5lYEcgIPzBmeeiu7K2rAS0c3C9KNeh10cEORXEHivwsGhgH0aFuOXd80adgCcrzJdXqElQJm7rrL1oFvzLqYKv9t1GnwWmr7nf0cfSVeMMvf3BbjQ68se99JuPM4egRI2anH5CP0banZb5e0b0bWyB6sLYCgVd26aO9hZNPOeLdKXk8H0c3tkZm42fDpyZ10b3mExe2XILDjA7p9pfsFp6S7rErv0b0bgc19YXfE0cu3xj9Y5H3zqodhNAsICDAoV6w8LkwB6m0cF8S0cpKk0bc1dMss9P0aPRrLuRuCn5jNXzP5QLvBQumtYhFANQinKzSpddIG19LRqt4jIZI1QOF7vEecEjQ2PGe0a0c9wAYeMzfo9F6HWy2CPedUGJnEO86FEpoJlUhhqBYKaSQ3zQzdebmtXuxW63r6LuagoUnEwodg20cOAR0cYeuvynTZa1UYjls30aDvK1m3cWDZRFQPU0akp0aThIrpRDPvhNiLGlHEKBCfiQjqCsWiTvZwqRnUCDSZGUIpL8kX2uQqm50cajSKacJ0aYwlVAjJBG8G0ccwNaFsQo0afkttqN7f43tIJm0cCJgEGkcIsBqLd7GCsphKizZW8DgYg7yRCibBfhdjjWeqSuIyjT4RboZpt1Ykg9PdTOBX2JziPgTulyd7ewNRpqiNv70avb40aCQBA0cZzmXQQapZwoxPFGfQPs0cMYLWltknGkhdSJZJ0azEcpymrBEaQkd3yGtyTjSRHIplIplioMMaBR7SRXhXdJSjSJNlUgoyETnvINWAlhFpcSTGl3SXI8jDeKuBYmOUghgCDHAbsKAuOqRZmwUaQNkeSJj6U5AB0bDhCsETpWiXMqWjKAuQDp50a1AzIl9YyMQaYJbvyAaI9irKMWYzvPYT7H51Eg55pzD5yuamGNBu7YmHukBQS2g5CpYVM7Lx6f0c0cYIDLBaEcASMIEk5xJBl1Si20aAjR0bF1qGXEJBfAtJqB5kwo7HBGDEiliBKFYexpo2ShPagsaPQoo5geGrJKK2gpUprPR4Y5VJ21IhKYGgQniDbeA8ZPYqsI3Yg0aMgyIiUXiUpGQ4OnmQ5JqSmOWtB8CQHTwfv9eQwZFQNWfRwYZmS8R1tMBdWgrkFYmSbQrMeCYcN7vkeBYUTzuPsNs5v3oMckOBOPByOfDIZChd1hwiUQBGXDNGVP4Ix5MpiE0aSRmDDcGYIAuTMDGJA0cN1sLI8EqKY6APBNwW0aXFbKOEMdDBYMqqkEQ97VJHRnUFlNGgnThLoJZLE9gLUk95Te9TJZqokiD20aBjqbg0bnZUznXQsQmhYLxBqUApjAhOq6ccUP3VN5RMIKh8wMaFZhCE0bv9DcomsLljhQmYUEOhZyRrxkljdiyfjjcd5Bt4Z4gB48XAZlK0bp0cYkRq2moKmVQAkgYPZUVLlAwzNYt0b5aEUnBfYK2S8L29rkiLK4aLYXBUalY19xyJsYwnaOrqxNCKVhE8D0c5vrrBkHTeg8AAeMsNl8rwTo8PDjqou2uHATc14FEqjtt15Z66wauIxwi4GNBkcI9okpiOayT3CZvpjFowP0bBiKTCR4MSpfbIWA5ZgRnFu2B3cCTbQcnQiw3X7yAmLtTqwkkkFQyiBSO2hPfcztHYBuCMIegoqwVDQw3iHB29H20a0aVDw9zggflp0c4w2n1heXWzyLcv0ca5L40c2rY0cCJMBhN0aiBcH0aLOOm4cji0aFf4GWSHj0a7qfuwhBItezoe4kaAboLBpmkJng9ajbl6Ac0ahzna7mH2KDTOOl4U7cLbMlgspQqEH0bwl5zAMsepRy1VF9sm2Gv0c9r122yy7Lbe4CY9x0bneLKwzJHV5fW61TXGW6HYKCqIbrb4n7g7T0cg5fNlbud7GHK1XFdtGIdRXHMVnMdudov5iZ3OuZX6EEIv0cGyOge0bqEuLZbLP9tfDGDspWuAJ58TGrexPeSTe0cFlcxVV0b6rVI8ZFWft0ag0cXxSVm220ajgcwBZ74Kd8EO4ftXscqXa1v7tf1auusXK3SraddQr9ugjancHGXzeelx0bl3UQOAzFfv57suPudtfb70a2kHt7Fwc4GO4gwUns9JZFu0cDbudcgtLfinnZFCzSzTY8qzbYM0cVl1ITg5Iw0cjmc3D2Wfq0cNyWW48lxYZyPXGl7cOyyKfZ36x0b6zd1HdVfmpfLqsP2b20cRNn9OZ0cPg92JBUiqY80cp9SyH1xHVKYLerrPZ66IqLzdllc2qaAtxtbk0cb7qmU9zORTYL1Yvy0a9ly6W94NHgDNzHcZMXVrthebpDeXVZP2fkldRy0aV3bgynq1s0cKnNOwGnwTsEv6AO4CnDGj0ajNNXqEwNhtcQv8EjENiYix90a0azX90ax6x0bVAPQZ90baQePe8kf86QcAnkw6hCYCNRgmC0cBbS1zW3ZA3itL0cnRu12ROqv0cO0a5Pfd6CJ5ieUTkD7czYBbQFmTdGJZhPDJgmbUHAFKNwHn2cCWm9CBfyBZyg8BEHDRLEJ3IEbUA51UsX0bIL8Xvo7qUB18YvgkgZcI0c5o60akN10aAk4hQnQga75qnZQQ50blKRMgHFeVP7Yq0bBdpCf7YqtIjrXo687CqoKJsjUHTs0cFvQgEko3gPf0bfwr5hgwMOgEnRs0aCljXESIwI6EgBwmirCAMJD34KCOcfgQDGBsAEFkMWGkM5YsygaZZQQLEFuU8DtcMxXxP0bq3HdiV58QewYlqfnLFERPGCVaHnY5zvMM5x2IHGbkm4b6HH0aHPZuZreDYwyA7z7PcCdfVJ4z0be0aIyRk88ntXtc3238AbjLw5uf0arzyN0cuUaEzq0ayJfQhPR7zupKtfK2QmEyidffi9OTupFg5OitGRRm0c1ePCBCX72zuF1Q5e3t70aV0bW1MOFvSaKlRdAzyTzejQE9I90aIJAu9OUgKXE99xlt40ayaiI0bYdGvs2KeF3f9urK6c6V7uNe0ak5MH0cMvDZUNweR9u1YHLhuFS0bTS4fCRcPpK7aQcu38Pd52RuVxKZZPv52h0aHoovsiPB78HGtGdZ6GO2AsLsmOI7LJ3Jc0cjXyrJ440cNQw3D1Mft7hNwB35PB7Xu560aWqACqaPSPRhgT0aq9CFV60av1CdcCu0af6AeETpH0bwBt9nZqjPhoZ27iE33WYe0aylHxq3HI8bKUB0bPeA6Z1qM1Rg0bPfn4trPmgzMbSFcgkHadmgewhmfLMSUYP0bB5zkudnjtGDJmovc9Qo3gDVRw0cC1p8iQxyjo8SJkidxAecnGvrdFg8YhEG3M6Qx4Hu6UNDdfhiqyau1o8NtUB0aNSJTXPk9SRk0bTp0bQAJ0cVITibHOAkhbMTIAYx7uBtBX3vZautruYfBpitz0b9ZOmknN0aXWiKuk1eYeZHXsDhk4F2MLnaXPYKN8mJxJxk9aYr0bOEbUeK4fA4HZLDFnx3nH5bO0aTHhmJDiOizIBrr7g0ahYo9ANAKQk7xsHbcEfDAyJP4BoAiAfx90bC8VGHhGbngz2JTCUvx6ZBz0bzEMt3z3M79UlyihQ3CZxiLtVqmc1Pbfasys5qfznN5nlVbq7tVLF90brZcLstPF50bz2c7NzbsJ89tyM8u6SzFNYpyN3WUdnH9NMUES7tauyvUvuE3cV2CPKqd5kc1x6eIsSjUcrolEh6PeNqeycYVL19mIcGNfPv980biNvt6KT5sQ0alCZT5tLTQNt9ogpcwm1J8ZoSrym1m9pxNbShJEJKdmdpREXgFglWczupKdEWU0aBJCntwwVFyC5IRKcYxaZKFRGpCrCUkA0aJ8KjyhMB2LPZ6xsVve69W0aV1ESibzARbdycx8zlRFFpcFtkcS0ayZWwfhlt9G0cqJ1NCJO5gIloYQTTDpW0aPqD1OH7VOScmbvqup65bhLXFGDnMpoCNqOsrT4REdMZJOIwBikI45TEeQpCZDm16jbf8ngUjSKfeEfA6hWCQTpZou0aE0aXeFqBBFAeCOVBUTKNJLWNUy0adtU0bQIlR10bxrpFmyoedRM1bERx5hpBKzhOQ0akLBAxpYMGDjNL1KRkA4sPdR0cnR2FJkxhWs0av1Bl7AdaGCHhzgeth9VPV1QdA0bpjBb0bQFStCbTyDhnw3ouHC197cTstmNLyAvCMCBgeHJcFGy29IZiXwMH4sDkYV41vUd999HBBsIwNo0coP9bolkCZB9SUnMpRbG9GHw9QiUADy6D70bmynxONp0bo0bxQUKgFPRxtquGmmcWGeK55gGqfUOw6T7mRT0aYgToS9jECwVnTkQ3n2aA80aCQYh0ctVTY3Ns38YG1hS0a2H0cO3vm3G0aXcPsQiN3r8HWnDuuV9xFnEHd2b4Y90aovbI6zdddnytpdpgQ1wXlP0b5jxdN1U3SYPb82lx0bdXxY0cDBs0c1jT92sxO0aN3MNg9wnN8ewPpQy3KNjPLJQfHfjtr0aW90cyLcwoL7G3yGyc7xlh9ovJuKK46buROW1JsnrvPVzh7Q8Yc0aNx0bOHqWn0cmCeYwKu0bIH441ohIXbdjk1ApkE8JJ0bADZB6oslEyokUuO6ocRlPwlu4Vsjhj4A0cciLERMDf6p3v5eEzgjzeCpnYrJvRKR0a0bqf9712xdaT3hbFYW81fg0aG9z3KPzA5kmGpwtaZjCzcYKlfrWHVA1jCdUENyBjLtTXnV2AQU7Wq5BvN6nm1qqSOf8Dh57kb6sJxR4ykPohyh9gj1T2W4ywcvuuadExl0cQkNOE485AzRIN0cp9Biu49d1LzoEolT1Kp387xH9JZT1dZXxkANGda36zy4sCmUPD4Ey0a0aJVozxZwY0bvf6PP8moc0azs3zQhP1ZPLdR5i8tS9rr7wL8NGZeRU6INXP0b1HadsMpfo8p1hzS1FJxzm4cHz4j0bZ0aryX8n7qmYjSwzu0bU7cj7LzLKvs3E0aGOF5TCHmZIEYJIzEdstsAGeaLfvulPoI7u30bVdvURFd2vKDEjDOh0cwSjheIrV5v0aJtlL2afDOYRIwg9pQQE2Uxv39oWhQKiHKlf6rE0b4S2bcfY3cjO5sSkQgqOKHUYHj2bSECNwGUh1hfHobIdXyuROHXrAQhIAlg0c8GefmuImrIQor0a8AlF0aD3ZLAX6LJlIpJfF83jfGyKVMgq5urg0bjZJ2zSWoKno9SoE8M5XjOQ35jlFK7M9BVeHkEo0bzKIzihLKFSa264IuIbQ0awoxMu6ZWR9fRgkxb1s0acBG7xQP2BLCNOXyWw9sJoPwCdSIJOGPOIKWxMeBKXhGRAomJeFCUGmPq3xLtJyEaLnL0anYIoUxIVy7xGCq0aTCVKCPGN5dKE3LQXxxgoO4eU8FsJmJgeghMpufzGo3uQge0b80cQm0ce3DQ0cgxFhYdRDrwRwJrqBE8IUy4wCQEMyQuOk3fVgbuHGfsd4HeA3wF0bB0cgd4F8PsLUvV0b1Bq7dforgfA0coDTnAnywVjX9kOM2UQeXGjiVYcwqbkQns0cDVwE0cB6MYAozQhimLiyPn4xW0ahFOxkG0aOhFK0aNBNwxgqgUgvwWwvYOr7EJNDCDvTWXKE63sYoJ852BsCdxgoRjMQ3HT2tQykxgCbWMRBy0aAiCQUnUAra5yBGCwei2878uvlqmWTALwj2VM0a0aKnQrlHKKITcTXNuEJ0coi6aElozmaTBWlXwlWTUkCwYhUDiw3LVYzNRRCZ0cBdGTyTCNMHS8eDpVM5JuY5prUEwTwmFqsB4PFw1xAEQmMMVUQmcmC4y9Fw9VR8LdpkKqRQ0aNF1CBaAFdMEE4aZRBJNDScDckAPSm0anVkjI18qBFlRrTMRnf0bwiSsNXoQiD0bAOGGUQ5YoCr9BFIxYhA6PDookoLnoQqQGM6LEwgoq28IsRgPvRlnbMb1CNPMFOAwgkXxflF0aj50auUzv8SH0cQe6Ei0bALdJhXvP1UQrOc0a1tdGMgz4J0c8Z9pJd0ayJ6kwIKVBtYBC4Bnsg3OfY8fXXoyuyT2I61nJXvUk0cn43IsGxf89HiZbZ5czyhZ0cDO0cVUg7kn7c4FCET6375kVwOzkHeVgtTV0aaMwclhCuFMHEQUphMAxvvu6sqMWJK2RXxN2R8XpqhPLEW7nujQfX40bE3yfZ0aBOWYdSdOxGNw3xcIkMGz49yEfdMXAny0cm5hOEjAd0bDKqBzu9ivkuXuzum3YwzakO20cF0aLn4Fe3rLmz3udGeO0afoxIADSjXM3dkbdvuqny48JoAELII0aGDa0cBKBk7KxJQuG0csRHf6yz31KtBaZgpmjQtuEpyMA1u8d82wuwQvNFSsjaJgv1kiHwbZzwyMZejBTtoccEMTZZjEvG44q0bNexi9qRS8fy6yJGTv6WTQ7rozCxIQcZ5iF7bOBAUMF2NI4jx1DvhjQohQ8Qa20aTSsEr7bpYTtYecI6bqgSmFJLM3B3hdEidtiVINBxtZ2h7bSqUdwYXHJyUmaz1FVeM59VL35uPgKLCYAMdBoxmFyNMeq0b0bHjwgwUaxpQylIjOUE0aESWC0aSfhFKVS4lkpoEcQU0cA2KFkHhxK3iUNmD37hSs2Mw7RLp9H0aUUzHbwNkiLWZZlAI60bkiT0b8CETffi97oMfW0ak0bIx370bsizcabXbH0aSWSCdL72gyBuyAUGrijPXtIgq8jVq6b0bsljeh0cfctWkTn4SJgFe1EfJ0a2ifxqrsXw0b1JAZ5lNTNX5b0czIB0at7pAVbt0cKzSbLXm7Suzv70cRDiPiuyzG7aT1dhxk0bl41wfyKd6K7RwAwJbEltlQ5PuSJKUcfzybQKOEQRwbkBcN4ljcXsJtOxN0aLD0bd0bSLMlwT9IXhRK0avbPIvz29ugtKbTZ7O22wryxJz9Lz40bbT5BkJ3n0azD2260b3MHssAzzcgkIA8B2oYLZZrNNVsV7yd8yKSf1n3fNIz7f9ZfTBVtfpnfZ9td1VlhfiiTa5vT6mGefru3TN9ftN6IX5SebKCYWvUbIGxkaSMFTK4ahr54czfDX5DHazV3ul9WLOvmYUuiNZOvmGlxdjnsTfAFoQmk919sMXN35ZVq5DfU0beS8yaELtHAkKdLNiktXpYuojA6Dqg5zDp80bXJ8PmT0bjnyuAu0a4PN7CHqTB51lgebaIHZbA9xngy7vF7jB7Pz50bJ3UOtcEDZJhWrTegQJSfamw0bjgP6f0akS3op9Y4lrkiaMFAio0agrcYfACYGx76avVAxPAra7wC4UAp4IAmiZq0buJUH8AYACgK9fPhLeqKRHDl7cT2ePrekRCVCwpijzN275cF8T77pHnb0aZHFjIwGUARUnEQ0bsuzD54vaEV0blO0b0cJU9mIPxtUCPegda0cbdi7T5qXWvqj1n9IR7oE4oO9sP0cAbLTwWXljAAAEndOfSavefile``

**Comment by Calmcat5** [comment] 2023-03-28 16:51
i think i put an issue for this in earlier but it doesnt seem to exist. maybe i imagined it

**Comment by kajfik** [comment] 2023-04-04 09:45
Duplicate of https://github.com/antimatter-dimensions/mobile-issues/issues/579

**Closed as completed by kajfik** 2023-04-04 09:45 UTC
Labels: bug
