### ISSUE TITLE
Entering Cel7 dilation instantly creates huge jump in potential RS/s gained

### ISSUE THREAD

**Issue by msiitan** [antimatter-dimensions/mobile-issues#576] opened 2023-03-20 16:53 UTC
**Describe the bug**
When first entering Pelle's Dilation, the number of potential Reality Shards gained per second jumps instantly from ~1e39 to ~3e45. This happens even before the first Eternity in Dilation, i.e. before any TP or DT are generated. 

This makes obtaining the penultimate 1e45 RS upgrade trivial. Moreover, the potential RS/s gained doesn't jump again for a while (tested until 1e16 DT), eliminating the need for Armageddon and the 1e45 RS upgrade. 

**To Reproduce**
1. Open savefile below
2. Enter Dilation

**Expected behavior**
Like on Web, the potential RS/s gained should increase gradually based on DT, and shouldn't increase at all before any DT is generated. 

**Savefile**
https://paste.ee/p/ffPHv

**Additional context**
Prior to update 2.111.0i11, the jump was even greater: ~1e39 -> ~1e49

**Comment by kajfik** [comment] 2023-04-04 08:24
cannot reproduce
https://user-images.githubusercontent.com/20711517/229732791-72503581-d39c-4def-8be5-a45051e63deb.mp4

**Comment by kajfik** [comment] 2023-05-05 06:20
will close this for now

**Closed as completed by kajfik** 2023-05-05 06:20 UTC
Labels: bug
