### ISSUE TITLE
glyph filters dont give sacrifice points

### ISSUE THREAD

**Issue by arturritzel** [antimatter-dimensions/mobile-issues#594] opened 2023-04-28 14:27 UTC
**Describe the bug**
i am not gaining sacrifice points for glyphs when they are rejected by any filter; although manually sacrificing glyphs that have been passed by the filter gives me sacrifice points.

**To Reproduce**
1. select any glyph filter;
2. make sure the filter will choose the glyph (restart reality or enable automatic reality with any mode & any options);
3. auto-sacrificed glyphs (rejected by the filter) will not give you sacrifice points.

**Expected behavior**
those that were approved can be sacrificed manually and will earn points, and i expected the same from the filters. otherwise, there is no reason to the option "lowest total glyph sacrifice"

**Savefile**
https://pastebin.com/B5U1UUzm

**Additional context**
v2.111.0i16

**Comment by kajfik** [comment] 2023-04-28 17:32
Possible duplicate of #590

**Comment by kajfik** [comment] 2023-05-04 16:50
Fixed in 2.111.0i17

**Closed as completed by kajfik** 2023-05-04 16:50 UTC
Labels: bug
